name = "VecchiaMLE"
uuid = "499233a1-c46f-47cc-ab67-5a37788e9870"
authors = ["Caleb Derrickson <calebderrickson@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AdaptiveKDTrees = "68d1b5e8-2215-47d8-a76e-d1727e222b22"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AdaptiveKDTrees = "0.1.0"
CUDA = "5.6.1"
LinearAlgebra = "1.10"
MadNLP = "0.8.5"
MadNLPGPU = "0.7.7"
NLPModels = "0.21.3"
SparseArrays = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
